<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportType }} Report</title>
    <style>
        @page {
            margin: 0.5cm;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.2;
            margin: 0;
            padding: 10px;
            font-size: 9px;
        }
        .header {
            text-align: left;
            border-bottom: 2px solid #7c3aed;
            padding-bottom: 10px;
            margin-bottom: 20px;
            position: relative;
        }
        .header h1 {
            color: #7c3aed;
            margin: 0;
            font-size: 20px;
            text-transform: uppercase;
        }
        .header p {
            margin: 2px 0 0;
            color: #666;
            font-size: 10px;
        }
        .report-meta {
            position: absolute;
            top: 0;
            right: 0;
            text-align: right;
            font-size: 8px;
            color: #666;
        }
        .info-section {
            margin-bottom: 15px;
            background: #f8fafc;
            padding: 10px;
            border-radius: 6px;
            border: 1px solid #e2e8f0;
        }
        .info-grid {
            width: 100%;
        }
        .info-grid td {
            padding: 2px 0;
        }
        .label {
            font-weight: bold;
            color: #4b5563;
            width: 80px;
        }
        .value {
            color: #1f2937;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            table-layout: fixed;
            word-wrap: break-word;
        }
        .data-table th, .data-table td {
            text-align: left;
            padding: 6px 4px;
            border: 1px solid #e2e8f0;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
        .data-table th {
            background-color: #7c3aed;
            color: white;
            font-size: 8px;
            text-transform: uppercase;
            letter-spacing: 0.02em;
        }
        .data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 8px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }
        .status-badge {
            padding: 2px 4px;
            border-radius: 4px;
            font-size: 7px;
            font-weight: bold;
            text-transform: uppercase;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>SYNC</h1>
        <p>{{ $reportType }} Report - Tabular Data</p>
        <div class="report-meta">
            Generated: {{ $generatedAt }}<br>
            Created By: {{ $createdBy }}
        </div>
    </div>

    <div class="info-section">
        <table class="info-grid">
            <tr>
                <td class="label">Report Name:</td>
                <td class="value">{{ $reportName }}</td>
                <td class="label">Date Range:</td>
                <td class="value">{{ $dateRange ?: 'All Time' }}</td>
            </tr>
            <tr>
                <td class="label">Total Records:</td>
                <td class="value">{{ count($rows) }} {{ count($rows) >= 2000 ? '(Capped at 2000)' : '' }}</td>
                <td class="label">Filter Type:</td>
                <td class="value">{{ ucfirst($reportType) }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                @foreach($headers as $header)
                    @if(!in_array($header, ['id', 'created_at', 'updated_at', 'deleted_at', 'created_by_user', 'updated_by_user']))
                        <th>{{ str_replace('_', ' ', $header) }}</th>
                    @endif
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
                <tr>
                    @foreach($headers as $header)
                        @if(!in_array($header, ['id', 'created_at', 'updated_at', 'deleted_at', 'created_by_user', 'updated_by_user']))
                            <td>{{ $row->{$header} ?? '-' }}</td>
                        @endif
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This document is an official report generated by the ATSS FIBER Management System.</p>
        <p>&copy; {{ date('Y') }} ATSS FIBER. All rights reserved.</p>
    </div>
</body>
</html>
