ALTER TABLE service_orders 
ADD COLUMN IF NOT EXISTS new_router_modem_sn VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS new_lcp VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS new_nap VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS new_port VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS new_vlan VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS router_model VARCHAR(255) NULL;
